name: wr153
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.8
  - appdirs=1.4.4
  - asttokens=2.0.5
  - attr=2.5.1
  - backcall=0.2.0
  - black=22.6.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.5.0
  - fftw=3.3.10
  - flit-core=3.8.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.25.0
  - freetype=2.12.1
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - graphite2=1.3.13
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.33
  - harfbuzz=6.0.0
  - icu=70.1
  - idna=3.4
  - importlib_resources=5.2.0
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.10.0
  - ipywidgets=8.0.4
  - jack=1.9.22
  - jedi=0.18.1
  - jpeg=9e
  - jupyter_client=7.4.9
  - jupyter_core=5.3.0
  - jupyterlab_widgets=3.0.5
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.67
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libdb=6.2.32
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libgpg-error=1.46
  - libiconv=1.17
  - libllvm10=10.0.1
  - libllvm15=15.0.7
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.2
  - libsndfile=1.2.0
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=253
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=253
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpg123=1.31.3
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nspr=4.35
  - nss=3.89
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=3.1.0
  - packaging=23.0
  - pandas=1.5.3
  - parso=0.8.3
  - pathspec=0.10.3
  - pcre=8.45
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.0.1
  - pixman=0.40.0
  - platformdirs=2.5.2
  - ply=3.11
  - pooch=1.4.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - pytesseract=0.3.10
  - python=3.8.16
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2022.7
  - pyzmq=23.2.0
  - qt-main=5.15.8
  - qt-webengine=5.15.8
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.28.1
  - scipy=1.10.0
  - seaborn=0.12.2
  - setuptools=65.6.3
  - sip=6.7.7
  - six=1.16.0
  - sqlite=3.41.1
  - stack_data=0.2.0
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing_extensions=4.4.0
  - urllib3=1.26.14
  - wcwidth=0.2.5
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - wordcloud=1.8.2.2
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.10
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.4
  - pip:
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - async-timeout==4.0.2
      - attrs==22.2.0
      - backoff==2.2.1
      - cachetools==5.3.0
      - cohere==4.1.3
      - frozenlist==1.3.3
      - google-api-core==2.11.0
      - google-auth==2.17.0
      - google-cloud-vision==3.4.1
      - googleapis-common-protos==1.59.0
      - grpcio==1.53.0
      - grpcio-status==1.53.0
      - multidict==6.0.4
      - opencv-python==4.7.0.72
      - pdf2image==1.16.3
      - pillow==9.4.0
      - proto-plus==1.22.2
      - protobuf==4.22.1
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - rsa==4.9
      - yarl==1.8.2
